# Generated by Django 3.2.8 on 2021-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=120)),
                ('book_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
