# Generated by Django 3.2.8 on 2021-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211009_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='date',
            field=models.DateField(blank=True, default='2021-09-09'),
            preserve_default=False,
        ),
    ]
